name: TRAVELMATE-CICD

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

# Env
env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE_PATH }}
  DOCKER_CONTAINER: nest-server

jobs:
  job_install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout current commit (${{ github.sha }})
        uses: actions/checkout@v3

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: YuuuJeong
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and Push Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

      - name: Generate deploy.zip
        run: zip -r deploy.zip . -x '*.git*' -x '*.github*'

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zipfile
          path: deploy.zip

  deploy:
    needs: job_install_dependencies
    runs-on: self-hosted
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: zipfile

      - uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: ap-northeast-2
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-753362004828
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
